services:
  app:
    build:
      context: .
      dockerfile: ShelkovyPut_Main/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=nguyenquocbinh214@BB
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P nguyenquocbinh214@BB -Q 'SELECT 1'"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
    driver: local
